// Purpose: Contains the data for the application.

export const interiors = [
  { id: 1, name: 'Living Room', image: 'assets/images/1.jpeg' },
  { id: 2, name: 'Dining Room', image: 'assets/images/2.jpeg' },
  { id: 3, name: 'Kitchen', image: 'assets/images/3.jpeg' },
  { id: 4, name: 'Bedroom', image: 'assets/images/4.jpeg' },
  { id: 5, name: 'Bathroom', image: 'assets/images/5.jpeg' },
  { id: 6, name: 'Patio', image: 'assets/images/6.jpeg' },
  { id: 7, name: 'Balcony', image: 'assets/images/7.jpeg' },
  { id: 8, name: 'Garden', image: 'assets/images/8.jpeg' },
  { id: 9, name: 'Garage', image: 'assets/images/9.jpeg' },
  { id: 10, name: 'Basement', image: 'assets/images/10.jpeg' },
  { id: 11, name: 'Attic', image: 'assets/images/11.jpeg' },
  { id: 12, name: 'Hallway', image: 'assets/images/12.jpeg' },
  { id: 13, name: 'Stairs', image: 'assets/images/13.jpeg' },
  { id: 14, name: 'Laundry Room', image: 'assets/images/14.jpeg' },
  { id: 15, name: 'Home Office', image: 'assets/images/15.jpeg' },
  { id: 16, name: 'Library', image: 'assets/images/16.jpeg' },
  { id: 17, name: 'Playroom', image: 'assets/images/17.jpeg' },
  { id: 18, name: 'Home Gym', image: 'assets/images/18.jpeg' },
  { id: 19, name: 'Home Theater', image: 'assets/images/19.jpeg' },
  { id: 20, name: 'Game Room', image: 'assets/images/20.jpeg' },
  { id: 21, name: 'Mudroom', image: 'assets/images/13.jpeg' },
  { id: 22, name: 'Wine Cellar', image: 'assets/images/2.jpeg' },
  { id: 23, name: 'Sauna', image: 'assets/images/5.jpeg' },
  { id: 24, name: 'Spa', image: 'assets/images/8.jpeg' },
  { id: 25, name: 'Bar', image: 'assets/images/12.jpeg' },
  { id: 26, name: 'Pantry', image: 'assets/images/17.jpeg' },
  { id: 27, name: 'Closet', image: 'assets/images/16.jpeg' },
  { id: 28, name: 'Walk-in Closet', image: 'assets/images/20.jpeg' },
  { id: 29, name: 'Dressing Room', image: 'assets/images/2.jpeg' },
  { id: 30, name: 'Foyer', image: 'assets/images/3.jpeg' },
  { id: 31, name: 'Sunroom', image: 'assets/images/6.jpeg' },
  { id: 32, name: 'Porch', image: 'assets/images/9.jpeg' },
  { id: 33, name: 'Veranda', image: 'assets/images/14.jpeg' },
  { id: 34, name: 'Deck', image: 'assets/images/20.jpeg' },
  { id: 35, name: 'Terrace', image: 'assets/images/1.jpeg' },
  { id: 36, name: 'Pergola', image: 'assets/images/12.jpeg' },
  { id: 37, name: 'Gazebo', image: 'assets/images/3.jpeg' },
  { id: 38, name: 'Greenhouse', image: 'assets/images/11.jpeg' },
  { id: 39, name: 'Conservatory', image: 'assets/images/12.jpeg' },
  { id: 40, name: 'Orangery', image: 'assets/images/6.jpeg' },
  { id: 41, name: 'Atrium', image: 'assets/images/15.jpeg' },
  { id: 42, name: 'Courtyard', image: 'assets/images/11.jpeg' },
  { id: 43, name: 'Patio', image: 'assets/images/16.jpeg' },
  { id: 44, name: 'Balcony', image: 'assets/images/1.jpeg' },
  { id: 45, name: 'Garden', image: 'assets/images/20.jpeg' },
  { id: 46, name: 'Garage', image: 'assets/images/19.jpeg' },
  { id: 47, name: 'Basement', image: 'assets/images/18.jpeg' },
  { id: 48, name: 'Attic', image: 'assets/images/5.jpeg' },
  { id: 49, name: 'Hallway', image: 'assets/images/17.jpeg' },
  { id: 50, name: 'Stairs', image: 'assets/images/16.jpeg' },
  { id: 51, name: 'Laundry Room', image: 'assets/images/3.jpeg' },
  { id: 52, name: 'Home Office', image: 'assets/images/14.jpeg' },
  { id: 53, name: 'Library', image: 'assets/images/13.jpeg' },
  { id: 54, name: 'Playroom', image: 'assets/images/11.jpeg' },
  { id: 55, name: 'Home Gym', image: 'assets/images/8.jpeg' },
  { id: 56, name: 'Home Theater', image: 'assets/images/6.jpeg' },
  { id: 57, name: 'Game Room', image: 'assets/images/8.jpeg' },
  { id: 58, name: 'Mudroom', image: 'assets/images/19.jpeg' },
  { id: 59, name: 'Wine Cellar', image: 'assets/images/20.jpeg' },
  { id: 60, name: 'Sauna', image: 'assets/images/15.jpeg' },
];
